### ISSUE TITLE
[BUG] terrain console: MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by taitruong** [terra-money/terrain#94]
### Issue description
terrain console can not be started due to 

### Steps to reproduce the issue
Following steps as described in https://docs.terra.money/docs/develop/terrain/using-terrain-localterra.html

Start localterra:
1. git clone --depth 1 https://github.com/terra-money/localterra
2. cd localterra
3. docker-compose up

Create new dapp
1. terrain new counter (instead of my-terra-dapp, see bug #93)
2. cd counter
3. npm install
4. terrain deploy counter --signer test1
5. terrain console

Then I get this error:
`$ terrain console

    Error: Cannot find module '/home/ttruong/data/development/counter/lib'
    Require stack:
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/lib/commands/console.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/p
    lugin.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/c
    onfig.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/i
    ndex.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/command/lib/
    command.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/command/lib/
    index.js
    - /home/ttruong/.nvm/versions/node/v16.13.2/lib/node_modules/@terra-money/terrain/bin/run
    Code: MODULE_NOT_FOUND
`

### Tools and operating system versions
$ npm -v && node -v && docker-compose -v && docker -v && terrain --version
8.1.2
v16.13.2
docker-compose version 1.28.5, build c4eb3a1f
Docker version 20.10.17, build 100c701
@terra-money/terrain/0.4.1 linux-x64 node-v16.13.2

**Comment by dawiddrzala** [comment]
this is on tag 0.4.1 or the main branch ? console was not working on 0.4.1 with external lib

**Comment by emidev98** [comment]
I do not know yet since the next version will contain Rust workspaces which is a compplex feature to implement but is being developed here https://github.com/terra-money/terrain/pull/86.

You can use main branch in your local environment and you'll be in the bleeding edge ;)

**Comment by taitruong** [comment]
> I do not know yet since the next version will contain Rust workspaces which is a compplex feature to implement but is being developed here #86.
> 
> You can use main branch in your local environment and you'll be in the bleeding edge ;)

And how do I build a new terrain using main branch? Looking at the scripts in package.json I have no idea resp. can't find a build script :).

**Comment by taitruong** [comment]
Thanks for the info: https://github.com/terra-money/terrain/#use-terrain-main-branch-locally

**Comment by HeliosDigitalLabs** [comment]
I'm having this issue now and using the main branch doesn't seem to help. Just to be sure, where should the repo be cloned? I've tried everywhere I can think of, none of which worked, but I'm assuming the issue is that I'm not cloning correctly unless the original bug still needs to be fixed.
